config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'
 
  devise_for :users
  resources :experiments 
  get '/search' => "experiments#search"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branche.rb
class Branche < ApplicationRecord
 has_many :experiments
end

app/models/collage.rb
class Collage < ApplicationRecord
 has_many :experiments
end

app/models/experiment.rb
class Experiment < ApplicationRecord
    belongs_to :user
    belongs_to :lab
    belongs_to :sem
    belongs_to :branch
    belongs_to :collage 
end

app/models/lab.rb
class Lab < ApplicationRecord
  has_many :experiments
end

app/models/sem.rb
class Sem < ApplicationRecord
 has_many :experiments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  
  before_action :find_experiment, only: [:show, :edit, :update, :destroy]
 
  def index
   @experiments = Experiment.where(published: true)
     if params[:lab].blank?
        @experiments = Experiment.all.order("created_at DESC")
     else
    @lab_id = Lab.find_by(title: params[:lab]).id
    @experiments = Experiment.where(:lab_id => @lab_id).order("created_at DESC")
   end
  end
 
  

  def search    

     # @experiments = Experiment.where(title: params[:title])
    
      @experiments = Experiment.where("title LIKE ?", "%#{params[:title]}%")
      render "index"
     
  end

  def show 
     @experiments = Experiment.where(published: true)
  end

  def new 

    @experiment = current_user.experiments.build
    @labs = Lab.all.map{ |c| [c.title, c.id] }
    @sems = Sem.all.map{ |c| [c.name, c.id] }
    @collages = Collage.all.map{ |c| [c.name, c.id] }
    @branches = Branch.all.map{ |c| [c.name, c.id] }
    
  end 

  def create 
     @experiment = current_user.experiments.build(experiment_params)
     @experiment.lab_id = params[:lab_id]
     @experiment.sem_id = params[:sem_id]
     @experiment.branch_id = params[:branch_id]
     @experiment.collage_id = params[:collage_id]
       if @experiment.save
         redirect_to root_path
       else
       render 'new' 
      end
  end 
 


  def edit
   @labs = Lab.all.map{ |c| [c.title, c.id] }
   @branches = Branch.all.map{ |c| [c.name, c.id] }
     @sems = Sem.all.map{ |c| [c.name, c.id] }
     @collages = Collage.all.map{ |c| [c.name, c.id] }
  end

  def update
       @experiment.sem_id = params[:sem_id]
         @experiment.collage_id = params[:collage_id]
       @experiment.lab_id = params[:lab_id]
       @experiment.branch_id = params[:branch_id]
    if @experiment.update(experiment_params)
       redirect_to experiment_path(@experiment)
    else
      render 'edit'
    end
  end
    

  def destroy
    @experiment.destroy
    redirect_to root_path
  end
  
  private 
  def experiment_params
    params.require(:experiment).permit(:title, :description, :youtube_link, :lab_id, :sem_id, :collage_id, :branch_id, :published)   
  end
  def find_experiment
   @experiment = Experiment.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

 def index
    @experiments = Experiment.all    
    if(params[:query] && params[:query] != '')
      @search_query = params[:query]
      @experiments = Experiment.where("title LIKE ?" , "%#{@search_query.downcase}%")
      # @posts = Post.where(title: @search_query)
      respond_to do |format|
        @response = {status: "SUCCESS", experiments: @experiments}
        format.json {render json: @response}
      end
    end
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/experiments/_form.html.erb


<%= simple_form_for @experiment do |f| %>
<div class="form-labels-on-top">
  <%= select_tag(:collage_id, options_for_select(@collages), :prompt => "Select your collage") %>
</div>
<div class="form-labels-on-top">
  <%= select_tag(:branch_id, options_for_select(@branches), :prompt => "Select your branch") %>
</div>
<div class="form-labels-on-top">
  <%= select_tag(:sem_id, options_for_select(@sems), :prompt => "Select your sem") %>
</div>
<div class="form-labels-on-top">
  <%= select_tag(:lab_id, options_for_select(@labs), :prompt => "Select your lab") %>
</div>
  <div class="form-labels-on-top">
  <%= f.input :title, label: "Experiment title:" %>
</div>
  <div class="form-labels-on-top">
  <%= f.input :youtube_link, label: "youtube video url:" %>
</div>
<div class="form-labels-on-top">
  <h3>Add content:</h3> 
  <%= f.hidden_field :description, label: "Add content :", :input_html => { :rows => 7 , :style => 'width: 98%'} %>
  <%= f.trix_editor :description %>
</div>
<div class="form-labels-on-top">
  <%= f.button :submit %>
</div>
<% end %>

app/views/experiments/index.html.erb
<!DOCTYPE html>
<html>
<head>
	 <meta charset="UTF-8">
     <meta name="description" content="about me">
     <meta name="keywords" content="HTML,CSS,Rails,Arduino projects">
     <meta name="author" content="sanjay pinnaka">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Practical hub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>

    <h1 class="current-lab"><%= params[:lab] %></h1>
    <% if @experiments.count == 0 %>
	<h1>There are no experiments currently in this Lab</h1>
    <% else %>
    <% @experiments.where(:published => true).each do |experiment| %>
   <h3><%= link_to experiment.title, experiment_path(experiment) %></h3>
   <% end %>
   <% end %>

</body>
</html>

app/views/experiments/show.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
		
		<title></title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

	<style type="text/css">
		@media only screen and (max-width : 640px) {

        .container {
            margin-top: 0px;
           }
 
	</style>

	</head>


	<body>
		
		<div class="site-content">

		

			<main class="main-content">
				<div class="page-head">
					<div class="container">
						
						<h1 class="page-title"><%= @experiment.title .html_safe %></h1>
					</div>
				</div>
                





                <div class="fullwidth-block">
					<div class="container">
						<div class="col-sm-6">
							<p>Sed ut perspiciatis unde omnis iste natus voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae.</p>
							
							<p>Nemo enim ipsam voluptatem quia voluptas aspernatur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur.</p>

							
							
						</div>
						  <div class="col-sm-6">
			
							<iframe  class="macbook" src='https://www.youtube.com/embed/<%= @experiment.youtube_link .html_safe %>?rel=0&autoplay=<%= params[:autoplay] || 0 %>' frameborder='0' allowfullscreen></iframe>
						</div>
					</div>
				</div>







				<div class="fullwidth-block">
					<div class="container">
						<div class="col-sm-6">
							<h2>Theory</h2>
							<p><%= @experiment.description .html_safe %></p>
							<p><%= @experiment.lab.title %></p>
						</div>
						<div class="col-sm-6">
							<h2>components used</h2>
							<p><%= @experiment.components %></p>
                 			<a><%= link_to "Back", root_path, class: "button" %></a>
							<% if user_signed_in? %>
                            <% if @experiment.user_id == current_user.id %>

                            <%= link_to "Edit", edit_experiment_path(@experiment) %>
                            <%= link_to "Delete", experiment_path(@experiment), method: :delete, data: { confirm: "Are you sure?" } %>
                            <% end %>
                           <% end %>

						</div>
						<%= render 'disqus' %>
					</div>
				</div>
	
			</main> <!-- .main-content -->
           

		</div> <!-- .main-content -->
		
    






		<script src="js/jquery-1.11.1.min.js"></script>
		<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en"></script>
		<script src="js/plugins.js"></script>
		<script src="js/app.js"></script>
		<script id="dsq-count-scr" src="//https-saipinnaka-herokuapp-com.disqus.com/count.js" async></script>
	
	</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <meta charset="UTF-8">
     <meta name="description" content="about me">
     <meta name="keywords" content="HTML,CSS,Rails,Arduino projects">
     <meta name="author" content="sanjay pinnaka">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Practical hub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>
  <style type="text/css">



  </style>
  <body>
  <a> <%= link_to "", root_path, id: "logo" %></a> 
  <nav>

  <input type="checkbox" id="nav" class="hidden"/>
  <label for="nav" class="nav-open"><i></i><i></i><i></i></label>
  <div class="nav-container">
    <ul>
        <li><%= link_to "Home", root_path, class: "current" %></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
        <% if user_signed_in? %>
          <li><%= link_to('signout', destroy_user_session_path, method: :delete) %> </li>
          <li> <%= link_to "Create experiment", new_experiment_path %></li>
        <% else %>  
          <li><%= link_to "Log In", new_user_session_path %></li>
           <li><%= link_to "Register", new_user_registration_path %></li>
           <li> <%= link_to "Create experiment", new_experiment_path %></li>
        <% end %>
    </ul>
  </div>
</nav>


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> 
  
    <%= yield %>
    

      <footer class="site-footer">
        <div class="container">
          <div class="row">
            <div class="col-xs-6 col-md-3">
              <div class="widget">
                <h3 class="widget-title">Contact</h3>
                <address>
                  <strong>Practical hub</strong>
                  <p>poranki,vijayawada, krishna district</p>
                  <p><a href="#">0000 0000 0000</a><br>
                  <a href="#">sanjaypinnaka@gmail.com</a></p>
                </address>
              </div>
            </div>
            <div class="col-xs-6 col-md-3">
              <div class="widget">
                <h3 class="widget-title">Help</h3>
                <ul class="dash-list">
                  <li><a href="#">Praesentium deleniti</a></li> 
                  <li><a href="#">Atque corrupti</a></li> 
                  <li><a href="#">Quos dolores quas molestias</a></li> 
                  <li><a href="#">Excepturi sint occaecati</a></li> 
                  <li><a href="#">Cupiditate provident</a></li>
                </ul>
              </div>
            </div>
            <div class="col-xs-6 col-md-3">
              <div class="widget">
                <h3 class="widget-title">About</h3>
                <ul class="dash-list">
                  <li><a href="#">something</a></li>
                  <li><a href="#">something</a></li>
                  <li><a href="#">something</a></li>
                 
                </ul>
              </div>
            </div>
            <div class="col-xs-6 col-md-3">
              <div class="widget">
                <h3 class="widget-title">Follow us</h3>
                <div class="social-links">
                  <a href="#"><i class="fab fa-facebook-f"></i></a>
                  <a href="#"><i class="fab fa-google-plus-g"></i></a>
                  <a href="#"><i class="fab fa-twitter"></i></a>
                  <a href="#"><i class="fab fa-github"></i></a>

                </div>
              </div>
            </div>
          </div>
        </div>
      </footer>


  <!--Start of Tawk.to Script-->
<script type="text/javascript">
window.$_API = undefined; 
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5ad849f25f7cdf4f05330b39/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->
          <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
    
    <title>practical hub</title>

  </head>
<style type="text/css">
  






</style>

  <body>
    
  
  <% if user_signed_in? %>
  <section class="main">  
   <div class="cover">
    <%= form_tag search_path, method: :get, class: "flex-form" do %>
    <%= text_field_tag :title, nil, placeholder: 'Search experiment' %>
    <%= submit_tag 'submit' %>
    <% end %>
  </div> 

   <div class="drop">
       <h1> select labs </h1>
       <div class="dropdown">
        <button class="dropbtn">Select your lab</button>
        <% Lab.all.each do |lab| %>
            <div class="dropdown-content">
             <a href="" class="<%= 'active' if params[:lab] == lab.title %>"><%= options_for_select(link_to lab.title, experiments_path(lab: lab.title)) %></a>
         <% end %>    
           </div>
       </div>
     </div>
   </section>
     <% else %>

    <div class="site-content">
      <main class="main-content">
        <div class="hero">
          <div class="container">
            <img src="assets/imac.png" alt="" class="imac">
            <div class="hero-content">
              <span>To continue</span> <br>
              <span>please login or create a new account</span>
            </div>
           
               <a><%= link_to "Log In", new_user_session_path, class: "button" %></a>
               <a><%= link_to "Register", new_user_registration_path, class: "button" %></a>

          </div>
        </div> <!-- .hero -->

        <div class="fullwidth-block">
          <div class="container">
            <div class="col-md-4">
              <div class="feature">
                <i class="feature-icon"><img src="assets/support.png" alt=""></i>
                <h2 class="feature-title">Support</h2>
                <p>Vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti.</p>
              </div>
            </div>
            <div class="col-md-4">
              <div class="feature">
                <i class="feature-icon"><img src="assets/experiment.png" alt=""></i>
                <h2 class="feature-title">Practical hub</h2>
                <p>Assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet voluptates.</p>
              </div>
            </div>
            <div class="col-md-4">
              <div class="feature">
                <i class="feature-icon"><img src="assets/about-us.png" alt=""></i>
                <h2 class="feature-title">About US</h2>
                <p>Praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident similique.</p>
              </div>
            </div>
          </div>
        </div>
      </main> <!-- .main-content -->
     </div>
   <% end %>

     <!-- .main-content -->
  </body>

</html>